services:
  - type: web
    name: medical-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 60
    envVars:
      - key: GEMINI_API_KEY
        value: your-api-key-here
      - key: PORT
        value: 10000
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract